# Generated by Django 3.2.6 on 2021-10-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0006_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like',
        ),
    ]
