# Generated by Django 3.2.6 on 2021-10-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_remove_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/post'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/profile'),
        ),
    ]
