# Generated by Django 3.2.6 on 2021-10-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0008_auto_20211005_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default/default.jpg', null=True, upload_to='static/images/profile'),
        ),
    ]
